#property strict

#define PAGE_READWRITE 0x04
#define FILE_MAP_ALL_ACCESS 0xF001F
#define INVALID_HANDLE 0xFFFFFFFFFFFFFFFF

#define MAX_HISTORY_DEALS 100
#define HISTORY_PERIOD_SECONDS 86400  // 24 hours

