namespace TradeDesktop.Application.Models;

// Nhánh TIME: Open / Normal Close / SOS Close / TP đều chạy chu kỳ theo thời gian giữ
// (HoldConfirmMs / CloseHoldConfirmMs) cộng MinStableSamples của Gap Stability.
// SignalCycleSize vẫn được load và ghi log để đối chiếu với nhánh TICK, nhưng KHÔNG
// tham gia quyết định signal trên nhánh này.
// Price-freeze dùng riêng OpenPriceFreezeMs / ClosePriceFreezeMs, KHÔNG fallback về hold-time.
public sealed record ConfigRecord(
    string Id,
    string SansJson,
    string? HostName,
    string PlatformA,
    string PlatformB,
    int Point,
    int OpenPts,
    int ConfirmGapPts,
    // Thời gian giữ tối thiểu của một Open Cycle. 0 = không yêu cầu thời gian.
    int HoldConfirmMs,
    // Price-freeze khi thực thi Open. 0 = tắt kiểm tra.
    int OpenPriceFreezeMs,
    int ClosePts,
    int CloseConfirmGapPts,
    double CloseTpProfit,
    double CloseConfirmTpProfit,
    double CloseMaxTpProfit,
    double LimitMaxTp,
    double SosTriggerAOpenDistancePts,
    int SosTriggerAfterSeconds,
    int SosCloseConfirmGapPts,
    int SosCloseGapPts,
    // Thời gian giữ tối thiểu của một Close Cycle (dùng chung cho Normal Close, SOS Close và TP).
    int CloseHoldConfirmMs,
    // Price-freeze khi thực thi Close. 0 = tắt kiểm tra.
    int ClosePriceFreezeMs,
    int StartTimeHold,
    int EndTimeHold,
    int ConfirmLatencyMs,
    int MaxGap,
    int LimitMaxGap,
    int MaxSpread,
    int OpenMaxTimesTick,
    int CloseMaxTimesTick,
    int OpenPendingTimeMs,
    int ClosePendingTimeMs,
    int DelayOpenAMs,
    int DelayOpenBMs,
    int DelayCloseAMs,
    int DelayCloseBMs,
    int OpenNumberOfQualifyingTimes,
    int CloseNumberOfQualifyingTimes,
    int IsShowConfig = 0,
    string CurrentTickA = "",
    string CurrentTickB = "",
    string CurrentSlots = "",
    int MaxLifeTimeBySecond = 0,
    double MinProfitToClose = 0,
    int MinBuyOpens = 1,
    int MaxBuyOpens = 3,
    int MinSellOpens = 1,
    int MaxSellOpens = 3,
    int MaxTotalOpens = 5,
    int OppositeSideLockSeconds = 300,
    int OppositeOpenMinDistancePts = 0,
    int RdStartSameActionLockSeconds = 3,
    int RdEndSameActionLockSeconds = 10,
    int RdStartPostCloseLockSeconds = 300,
    int RdEndPostCloseLockSeconds = 300,
    int RdStartPostOpenLockSeconds = 0,
    int RdEndPostOpenLockSeconds = 0,
    string ScheduleSleepingJson = "",
    GapStabilityConfig? OpenGapStability = null,
    GapStabilityConfig? CloseGapStability = null,
    int SignalCycleSize = 10);
