namespace TradeDesktop.Application.Models;

public sealed record ConfigRecord(
    string Id,
    string SansJson,
    string? HostName,
    string PlatformA,
    string PlatformB,
    int Point,
    int OpenPts,
    int ConfirmGapPts,
    int HoldConfirmMs,
    int OpenPriceFreezeMs,
    int ClosePts,
    int CloseConfirmGapPts,
    int CloseHoldConfirmMs,
    int ClosePriceFreezeMs,
    int StartTimeHold,
    int EndTimeHold,
    int StartWaitTime,
    int EndWaitTime,
    int ConfirmLatencyMs,
    int MaxGap,
    int MaxSpread,
    int OpenMaxTimesTick,
    int CloseMaxTimesTick,
    int OpenPendingTimeMs,
    int ClosePendingTimeMs,
    int DelayOpenAMs,
    int DelayOpenBMs,
    int DelayCloseAMs,
    int DelayCloseBMs,
    int OpenNumberOfQualifyingTimes,
    int CloseNumberOfQualifyingTimes,
    int OpenGapTick,
    int CloseGapTick,
    int CoolDownGapTick,
    int IsShowConfig = 0,
    string CurrentTickA = "",
    string CurrentTickB = "");
