namespace TradeDesktop.Application.Models;

public sealed record ConfigRecord(
    string Id,
    string SansJson,
    string? HostName,
    string PlatformA,
    string PlatformB,
    int Point,
    int OpenPts,
    int ConfirmGapPts,
    int HoldConfirmMs,
    int OpenPriceFreezeMs,
    int ClosePts,
    int CloseConfirmGapPts,
    double CloseTpProfit,
    double CloseConfirmTpProfit,
    double CloseMaxTpProfit,
    double LimitMaxTp,
    double SosTriggerAOpenDistancePts,
    int SosTriggerAfterSeconds,
    int SosCloseConfirmGapPts,
    int SosCloseGapPts,
    int CloseHoldConfirmMs,
    int ClosePriceFreezeMs,
    int StartTimeHold,
    int EndTimeHold,
    int ConfirmLatencyMs,
    int MaxGap,
    int LimitMaxGap,
    int MaxSpread,
    int OpenMaxTimesTick,
    int CloseMaxTimesTick,
    int OpenPendingTimeMs,
    int ClosePendingTimeMs,
    int DelayOpenAMs,
    int DelayOpenBMs,
    int DelayCloseAMs,
    int DelayCloseBMs,
    int OpenNumberOfQualifyingTimes,
    int CloseNumberOfQualifyingTimes,
    int IsShowConfig = 0,
    string CurrentTickA = "",
    string CurrentTickB = "",
    string CurrentSlots = "",
    int MaxLifeTimeBySecond = 0,
    double MinProfitToClose = 0,
    int MinBuyOpens = 1,
    int MaxBuyOpens = 3,
    int MinSellOpens = 1,
    int MaxSellOpens = 3,
    int MaxTotalOpens = 5,
    int OppositeSideLockSeconds = 300,
    int OppositeOpenMinDistancePts = 0,
    int RdStartSameActionLockSeconds = 3,
    int RdEndSameActionLockSeconds = 10,
    int RdStartPostCloseLockSeconds = 300,
    int RdEndPostCloseLockSeconds = 300,
    int RdStartPostOpenLockSeconds = 0,
    int RdEndPostOpenLockSeconds = 0,
    string ScheduleSleepingJson = "",
    GapStabilityConfig? OpenGapStability = null,
    GapStabilityConfig? CloseGapStability = null);
